name: Beacon Chain Light Client Prototype # Name of the workflow.
on: [push] # Action on which the workflow runs. Can be push, pull_request, page_build, or many others

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master # Checkout the master branch
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1 # Setup .NET Core
      with:
        dotnet-version: 6.0.101 # Change to your version of .NET Core
    - name: Build with dotnet
      run: dotnet build --configuration Release 
    - name: Publish Blazor webassembly using dotnet 
      #create Blazor WebAssembly dist output folder in the project directory
      run: dotnet publish -c Release --no-build -o publishoutput # Don't build again, just publish
    - name: Publish generated Blazor webassembly to Netlify
      uses: netlify/actions/cli@master #uses Netlify Cli actions
      env: # These are the environment variables added in GitHub Secrets for this repo
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
          args: deploy --dir=publishoutput/wwwroot --prod #push this folder to Netlify
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]' 
